### ISSUE TITLE
change text color in Github header dashboard "Learn Git and Github without any code!" 

### ISSUE THREAD

**Issue by KartikParmar1995** [Brettm12345/github-moonlight#53]
```css
.intro-shelf {
    margin-top: 0;
    color: rgba(27,31,35,.85);
    background-image: linear-gradient(180deg,hsla(0,0%,100%,0) 60%,#fff),linear-gradient(70deg,#dbedff 32%,#ebfff0);
    border-bottom: #fff;
}
```
![Screen Shot 2020-05-08 at 4 19 58 PM](https://user-images.githubusercontent.com/23227333/81446070-230dc800-9148-11ea-95f5-6208a389e308.png)
